"""empty message

Revision ID: 056c1e156133
Revises: 3e3696522f9c
Create Date: 2018-05-28 16:59:38.400647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056c1e156133'
down_revision = '3e3696522f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carga', 'descricao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carga', sa.Column('descricao', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
