"""empty message

Revision ID: 48aa720f858a
Revises: aec6a2d8bda6
Create Date: 2018-06-02 11:55:19.628213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48aa720f858a'
down_revision = 'aec6a2d8bda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_config', sa.Column('last_user', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_config', 'last_user')
    # ### end Alembic commands ###
