"""empty message

Revision ID: 9f6caee2c0d2
Revises: 
Create Date: 2017-05-20 11:10:47.169626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6caee2c0d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CLIENTE_FORNECEDOR',
    sa.Column('IDCLIFOR', sa.Integer(), nullable=False),
    sa.Column('NOME', sa.String(length=80), nullable=False),
    sa.Column('UFCLIFOR', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('IDCLIFOR')
    )
    op.create_table('EMPRESA',
    sa.Column('IDEMPRESA', sa.Integer(), nullable=False),
    sa.Column('NOMEFANTASIA', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('IDEMPRESA')
    )
    op.create_table('ITEM',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('CODIGO', sa.String(length=10), nullable=True),
    sa.Column('DESCRICAO', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('MARCA',
    sa.Column('IDMARCAFABRICANTE', sa.Integer(), nullable=False),
    sa.Column('DESCRICAO', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('IDMARCAFABRICANTE')
    )
    op.create_table('NCM',
    sa.Column('NCM', sa.String(length=8), nullable=False),
    sa.Column('DESCRICAO', sa.String(length=820), nullable=True),
    sa.Column('FLAGCARGATRIBUTARIAMEDIA', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('NCM')
    )
    op.create_table('PRODUTO',
    sa.Column('IDPRODUTO', sa.Integer(), nullable=False),
    sa.Column('DESCRCOMPRODUTO', sa.String(length=60), nullable=True),
    sa.Column('FABRICANTE', sa.String(length=40), nullable=True),
    sa.Column('PERIPI', sa.Integer(), nullable=True),
    sa.Column('PERIPISAIDA', sa.Integer(), nullable=True),
    sa.Column('IDCSTIPIENTRADA', sa.Integer(), nullable=True),
    sa.Column('IDCSTIPISAIDA', sa.Integer(), nullable=True),
    sa.Column('IDCODENQIPIENTRADA', sa.Integer(), nullable=True),
    sa.Column('IDCODENQIPISAIDA', sa.Integer(), nullable=True),
    sa.Column('FLAGTRIBUTACAOGRUPO', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('IDPRODUTO')
    )
    op.create_table('PRODUTOS_VIEW',
    sa.Column('IDSUBPRODUTO', sa.Integer(), nullable=False),
    sa.Column('DESCRICAOPRODUTO', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('IDSUBPRODUTO')
    )
    op.create_table('STOKY_COLABORADOR_POR_TAREFA',
    sa.Column('COD_TAREFA_CD', sa.Integer(), nullable=False),
    sa.Column('ONDA_ONDA_ID', sa.Integer(), nullable=True),
    sa.Column('CODIGO', sa.String(length=10), nullable=True),
    sa.Column('COD_COLAB', sa.Integer(), nullable=True),
    sa.Column('NOME', sa.String(length=45), nullable=False),
    sa.Column('TAREFAS_COD_TAREFA', sa.Integer(), nullable=True),
    sa.Column('DTHR', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('COD_TAREFA_CD')
    )
    op.create_table('STOKY_ONDAS_POR_CLIENTE',
    sa.Column('ONDA_ID', sa.Integer(), nullable=False),
    sa.Column('PEDIDO_ID', sa.Integer(), nullable=True),
    sa.Column('NUM_PEDIDO', sa.String(length=10), nullable=True),
    sa.Column('NOME_CLIENTE', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ONDA_ID')
    )
    op.create_table('WMS_COLABORADORES',
    sa.Column('COD_COLAB', sa.Integer(), nullable=False),
    sa.Column('NOME', sa.String(length=100), nullable=True),
    sa.Column('ATIVO', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('COD_COLAB')
    )
    op.create_table('WMS_REGIOES_SEPARACOES',
    sa.Column('COD_REGSEP', sa.Integer(), nullable=False),
    sa.Column('EMPR_CODEMP', sa.Integer(), nullable=False),
    sa.Column('DESCRICAO', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('COD_REGSEP', 'EMPR_CODEMP')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_grupo_de_vendedores',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('nome_grupo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('tbl_meta_logistica',
    sa.Column('id_meta', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('valor_meta', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_meta')
    )
    op.create_table('tbl_meta_vendas',
    sa.Column('id_meta', sa.Integer(), nullable=False),
    sa.Column('nome_meta', sa.String(length=120), nullable=False),
    sa.Column('dt_inicial', sa.Date(), nullable=False),
    sa.Column('dt_final', sa.Date(), nullable=False),
    sa.Column('valor_meta_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_meta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_meta'),
    sa.UniqueConstraint('nome_meta')
    )
    op.create_table('tbl_paramtros_metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=30), nullable=False),
    sa.Column('colaboradores_excluidos', sa.String(length=100), nullable=False),
    sa.Column('valor_meta_diario', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_tarefas',
    sa.Column('id_tarefa', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('lista_ids_wms', sa.String(length=100), nullable=False),
    sa.Column('valor_meta', sa.Float(), nullable=False),
    sa.Column('qtdade_min_colaborador', sa.Integer(), nullable=True),
    sa.Column('flag_meta_variavel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_tarefa')
    )
    op.create_table('tbl_vendedores',
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('id_vendedor_ciss', sa.Integer(), nullable=True),
    sa.Column('nome_vendedor', sa.String(length=120), nullable=False),
    sa.Column('flag_inativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_vendedor'),
    sa.UniqueConstraint('id_vendedor_ciss')
    )
    op.create_table('CONFERE_AUTORIZA',
    sa.Column('IDAUTORIZACAO', sa.Integer(), nullable=False),
    sa.Column('IDEMPRESA', sa.Integer(), nullable=False),
    sa.Column('NUMNOTA', sa.Integer(), nullable=False),
    sa.Column('SERIENOTA', sa.String(length=3), nullable=False),
    sa.Column('IDCLIFOR', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IDCLIFOR'], ['CLIENTE_FORNECEDOR.IDCLIFOR'], ),
    sa.PrimaryKeyConstraint('IDAUTORIZACAO', 'IDEMPRESA', 'NUMNOTA', 'SERIENOTA', 'IDCLIFOR')
    )
    op.create_table('PRODUTO_GRADE',
    sa.Column('IDSUBPRODUTO', sa.NullType(), nullable=False),
    sa.Column('IDPRODUTO', sa.Integer(), nullable=False),
    sa.Column('SUBDESCRICAO', sa.String(length=100), nullable=False),
    sa.Column('FLAGINATIVO', sa.String(length=1), nullable=True),
    sa.Column('NCM', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['IDPRODUTO'], ['PRODUTO.IDPRODUTO'], ),
    sa.ForeignKeyConstraint(['NCM'], ['NCM.NCM'], ),
    sa.PrimaryKeyConstraint('IDSUBPRODUTO', 'IDPRODUTO')
    )
    op.create_table('STOKY_METAS',
    sa.Column('IDPLANILHA', sa.Integer(), nullable=False),
    sa.Column('IDEMPRESA', sa.Integer(), nullable=False),
    sa.Column('NUMSEQUENCIA', sa.Integer(), nullable=False),
    sa.Column('IDVENDEDOR', sa.Integer(), nullable=False),
    sa.Column('DTMOVIMENTO', sa.Date(), nullable=True),
    sa.Column('IDSUBPRODUTO', sa.Integer(), nullable=False),
    sa.Column('IDMARCAFABRICANTE', sa.Integer(), nullable=True),
    sa.Column('VENDA', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('DEVOLUCAO', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('LUCRO', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['IDEMPRESA'], ['EMPRESA.IDEMPRESA'], ),
    sa.ForeignKeyConstraint(['IDMARCAFABRICANTE'], ['MARCA.IDMARCAFABRICANTE'], ),
    sa.ForeignKeyConstraint(['IDSUBPRODUTO'], ['PRODUTOS_VIEW.IDSUBPRODUTO'], ),
    sa.ForeignKeyConstraint(['IDVENDEDOR'], ['CLIENTE_FORNECEDOR.IDCLIFOR'], ),
    sa.PrimaryKeyConstraint('IDPLANILHA', 'IDEMPRESA', 'NUMSEQUENCIA')
    )
    op.create_table('WMS_PREDIOS',
    sa.Column('PREDIO_ID', sa.Integer(), nullable=False),
    sa.Column('COD_PREDIO', sa.String(length=4), nullable=True),
    sa.Column('RUASARM_COD_RUASARM', sa.String(length=5), nullable=True),
    sa.Column('REGIAO_SEPARACAO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['REGIAO_SEPARACAO'], ['WMS_REGIOES_SEPARACOES.COD_REGSEP'], ),
    sa.PrimaryKeyConstraint('PREDIO_ID')
    )
    op.create_table('tbl_erros',
    sa.Column('id_erro', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('id_tarefa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tarefa'], ['tbl_tarefas.id_tarefa'], ),
    sa.PrimaryKeyConstraint('id_erro')
    )
    op.create_table('tbl_meta_promocional',
    sa.Column('id_meta', sa.Integer(), nullable=False),
    sa.Column('nome_meta', sa.String(length=120), nullable=False),
    sa.Column('dt_inicial', sa.Date(), nullable=False),
    sa.Column('dt_final', sa.Date(), nullable=False),
    sa.Column('valor_meta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qtdade_meta', sa.Integer(), nullable=True),
    sa.Column('id_grupo_id', sa.Integer(), nullable=True),
    sa.Column('id_fabricante', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo_id'], ['tbl_grupo_de_vendedores.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_meta'),
    sa.UniqueConstraint('nome_meta')
    )
    op.create_table('tbl_meta_tarefa',
    sa.Column('id_meta', sa.Integer(), nullable=False),
    sa.Column('valor_meta', sa.Float(), nullable=False),
    sa.Column('id_tarefa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tarefa'], ['tbl_tarefas.id_tarefa'], ),
    sa.PrimaryKeyConstraint('id_meta')
    )
    op.create_table('tbl_metas_vendedor',
    sa.Column('id_meta_id', sa.Integer(), nullable=False),
    sa.Column('id_vendedor_id', sa.Integer(), nullable=False),
    sa.Column('val_meta_min_vendedor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('val_meta_vendedor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_meta_id'], ['tbl_meta_vendas.id_meta'], ),
    sa.ForeignKeyConstraint(['id_vendedor_id'], ['tbl_vendedores.id_vendedor'], ),
    sa.PrimaryKeyConstraint('id_meta_id', 'id_vendedor_id')
    )
    op.create_table('tbl_vendedor_identifier',
    sa.Column('id_vendedor', sa.Integer(), nullable=True),
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['tbl_grupo_de_vendedores.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_vendedor'], ['tbl_vendedores.id_vendedor'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('CONFERE_MERCADORIA',
    sa.Column('IDAUTORIZACAO', sa.Integer(), nullable=False),
    sa.Column('IDPRODUTO', sa.Integer(), nullable=False),
    sa.Column('IDSUBPRODUTO', sa.NullType(), nullable=False),
    sa.ForeignKeyConstraint(['IDAUTORIZACAO'], ['CONFERE_AUTORIZA.IDAUTORIZACAO'], ),
    sa.ForeignKeyConstraint(['IDPRODUTO'], ['PRODUTO_GRADE.IDPRODUTO'], ),
    sa.ForeignKeyConstraint(['IDSUBPRODUTO'], ['PRODUTO_GRADE.IDSUBPRODUTO'], ),
    sa.PrimaryKeyConstraint('IDAUTORIZACAO', 'IDPRODUTO', 'IDSUBPRODUTO')
    )
    op.create_table('PRODUTO_TRIBUTACAO_ESTADO',
    sa.Column('UF', sa.String(length=2), nullable=False),
    sa.Column('IDPRODUTO', sa.Integer(), nullable=False),
    sa.Column('IDSUBPRODUTO', sa.NullType(), nullable=False),
    sa.Column('PERICMENT', sa.Integer(), nullable=True),
    sa.Column('PERICMSUBST', sa.Integer(), nullable=True),
    sa.Column('PERMARGEMSUBSTI', sa.Integer(), nullable=True),
    sa.Column('PERMARGEMSUBSTISAI', sa.Integer(), nullable=True),
    sa.Column('IDSITTRIBENT', sa.Integer(), nullable=True),
    sa.Column('TIPOSITTRIBENT', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['IDPRODUTO'], ['PRODUTO_GRADE.IDPRODUTO'], ),
    sa.ForeignKeyConstraint(['IDSUBPRODUTO'], ['PRODUTO_GRADE.IDSUBPRODUTO'], ),
    sa.PrimaryKeyConstraint('UF', 'IDPRODUTO', 'IDSUBPRODUTO')
    )
    op.create_table('WMS_TAREFAS_CD',
    sa.Column('CENTDIST_COD_CENTDIST', sa.Integer(), nullable=False),
    sa.Column('COD_TAREFA_CD', sa.Integer(), nullable=False),
    sa.Column('EMPR_CODEMP', sa.Integer(), nullable=False),
    sa.Column('TAREFAS_COD_TAREFA', sa.String(length=6), nullable=True),
    sa.Column('LA_PREDIO_PREDIO_ID_ORIGEM', sa.Integer(), nullable=True),
    sa.Column('LIBERADA', sa.String(length=1), nullable=True),
    sa.Column('DTHR', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['LA_PREDIO_PREDIO_ID_ORIGEM'], ['WMS_PREDIOS.PREDIO_ID'], ),
    sa.PrimaryKeyConstraint('CENTDIST_COD_CENTDIST', 'COD_TAREFA_CD', 'EMPR_CODEMP')
    )
    op.create_table('tbl_registro_de_erros',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('id_onda', sa.Integer(), nullable=False),
    sa.Column('id_tarefa', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('id_produto', sa.String(length=10), nullable=False),
    sa.Column('id_erro', sa.Integer(), nullable=False),
    sa.Column('descricao_produto', sa.String(length=100), nullable=False),
    sa.Column('id_colaborador', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_erro'], ['tbl_erros.id_erro'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_registro_de_erros')
    op.drop_table('WMS_TAREFAS_CD')
    op.drop_table('PRODUTO_TRIBUTACAO_ESTADO')
    op.drop_table('CONFERE_MERCADORIA')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tbl_vendedor_identifier')
    op.drop_table('tbl_metas_vendedor')
    op.drop_table('tbl_meta_tarefa')
    op.drop_table('tbl_meta_promocional')
    op.drop_table('tbl_erros')
    op.drop_table('WMS_PREDIOS')
    op.drop_table('STOKY_METAS')
    op.drop_table('PRODUTO_GRADE')
    op.drop_table('CONFERE_AUTORIZA')
    op.drop_table('tbl_vendedores')
    op.drop_table('tbl_tarefas')
    op.drop_table('tbl_paramtros_metas')
    op.drop_table('tbl_meta_vendas')
    op.drop_table('tbl_meta_logistica')
    op.drop_table('tbl_grupo_de_vendedores')
    op.drop_table('roles')
    op.drop_table('WMS_REGIOES_SEPARACOES')
    op.drop_table('WMS_COLABORADORES')
    op.drop_table('STOKY_ONDAS_POR_CLIENTE')
    op.drop_table('STOKY_COLABORADOR_POR_TAREFA')
    op.drop_table('PRODUTOS_VIEW')
    op.drop_table('PRODUTO')
    op.drop_table('NCM')
    op.drop_table('MARCA')
    op.drop_table('ITEM')
    op.drop_table('EMPRESA')
    op.drop_table('CLIENTE_FORNECEDOR')
    # ### end Alembic commands ###
